slam_toolbox:
  ros__parameters:

    ## use_sim_time: true # simulator 사용시에만
    # ROS Parameters 프레임/토픽
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint ## -> body
    scan_topic: /scan
    use_map_async_plugin: False

    ## 오도메트리/TF(중요)
    ## use_odometry: true
    ## provide_odom_frame: true 
    ## publish_tf: true
    # Slam Toolbox Parameters
    mode: mapping # mapping or localization

    # Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 0.5    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: True

    # Scan Matcher Parameters
    do_loop_closing: True
    loop_search_maximum_distance: 3.0
    loop_search_skew_lib: 0.05
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.03 

    # Scan Buffer Parameters
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    # TF/시간 버퍼/대기
    tf_buffer_duration: 30.0 
    stack_size_to_use: 40000000 
    enable_interactive_mode: True

    ## 메시지 필터 (프레임 매치)
    ## queue_size: 100

    ## 스캔 특성/규격 변화
    max_laser_range: 20.0
    resolution: 0.05
    ## minimum_rage: 1.0
    ## throttle_scans: 2


    # General Parameters
    use_scan_matching: True
    use_scan_barycenter: True
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_iterations: 15
    max_get_map_retry_count: 3
